### ISSUE TITLE
Move Rate parameters into own namespace

### ISSUE THREAD

**Issue by irwineffect** [PalouseRobosub/robosub-2018#175]
Looking at cobalt.yaml right now, there are a lot of nodes that have their own rate parameter, so it looks something like:
```yaml
depth:                                                                          
    rate: 10                                                                    
sensor:                                                                         
    rate: 20                                                                    
    axis:                                                                       
        x: 1                                                                    
        y: 2                         
        z: 3                                                                    
control:
    rate: 10
    mass: 27.0
````

We want to reorganize all the rate settings to be underneath a single rate namespace, so it looks like:
```yaml
rate:
    depth: 10
    sensor: 20
    control: 10
```

Note this change involves more than just changing the settings file, it also requires going through all programs that load from the settings file.
