### ISSUE TITLE
Parameter Reorganization

### ISSUE THREAD

**Issue by irwineffect** [PalouseRobosub/robosub-2018#260]
Currently we group parameters like so:
```yaml
ports:
    bno055_left: "/dev/bno055_left"
    bno055_right: "/dev/bno055_right"
    trax: "/dev/trax"
rate:
    bno055_left: 20
    bno055_right: 20
    trax: 20
```

While it makes the parameter file easier to read, it makes code for loading parameters a little more complex, especially when we want to move nodes to different namespaces. I think we should reorganize it like so:

```yaml                                                                 
bno055_left:                                                                    
    port: "/dev/bno055_left"                                                    
    rate: 20                                                                    
                                                                                
bno055_right:                                                                   
    port: "/dev/bno055_right"                                                   
    rate: 20                                                                    
                                                                                
trax:                                                                           
    port: "/dev/trax"                                                           
    rate: 20 
```

This makes putting nodes in different namespaces WAY easier.
